### ISSUE TITLE
Flashing to Odroid-N2+ SPI fails

### ISSUE THREAD

**Issue by mth** [Tow-Boot/Tow-Boot#103]
[odroid-log.txt](https://github.com/Tow-Boot/Tow-Boot/files/8098820/odroid-log.txt)
Tried to flash the 2021.10-003 release to SPI on 4GB Odroid-N2+.

* Wrote the installer to SD card with dd
* Booted the SD card
* Selected `Flash firmware to SPI` (from menu)

This failed with `SF: 8388608 bytes @ 0x0 Read: ERROR -110`.

Then tried `Completely erase SPI`, this failed with "No SPI flash selected. Please run `sf probe' ".

Attached the serial console log. In the log Tow-Boot detects the board as Odroid-N2 without plus - maybe that is the problem?

**Comment by samueldr** [comment]
@strit recently faced similar, or the same, issue.

I don't have the hardware on hand to check. Though it has to be noted that SPI and eMMC shares something on the bus, which may be causing issues.

cc @tpwrules and @L-as

**Comment by Strit** [comment]
Yep, sounds like exactly the same issue.

Didn't matter how the SPI Boot Order Switch was set, it would always fail like OP mentioned.

**Comment by tpwrules** [comment]
It has detected the board fine, see `Board variant: n2-plus` on line 117 of the log. But in any case, I also have this problem. I booted with the SD card in, eMMC removed, and the boot switch set to MMC, then tried to flash from the menu and got this same error.

Commit 4425d07 which introduces N2+ support to Tow-Boot 002, flashes and boots from SPI correctly though following those same steps. I wonder if upstream 2021.10 broke something. I might be able to debug next week.

**Comment by samueldr** [comment]
Thanks for confirming @tpwrules, I guess yeah this could be bisected. I should look into ensuring the build tooling works without patches to build a stock U-Boot. It would help such endeavours.

**Comment by tpwrules** [comment]
I did some bisecting and U-Boot commit e2e95e5e breaks `sf probe`. They realized this eventually and U-Boot commit b81ce79d fixes that but `sf read` still doesn't work properly. My next step would be to figure out how the SPI controller was configured pre-e2e95e5e and why it's not that way post-b81ce79d but that will have to wait until next week sometime.

**Comment by tpwrules** [comment]
I lied again, oops. Please give this patch a try.

**Comment by L-as** [comment]
FYI flashing from Linux worked flawlessly for me as a workaround.

**Comment by tnytown** [comment]
FYI (if you don't have a SD card with Linux handy) it's also possible to flash Tow-Boot "manually" from the U-Boot console. All you have to do is to bring up the SPI flash with the correct clock speed:
```
sf probe 0 52000000 0
```

**Comment by mth** [comment]
> FYI flashing from Linux worked flawlessly for me as a workaround.

Succeeded with flashcp to mtd0 (after choosing spi capable dtb in armbian). :)

**Comment by samueldr** [comment]
Oh, this is now entirely fixed with #149 I believe.

**Comment by L-as** [comment]
Great!
