### ISSUE TITLE
Add the ability to change boot order

### ISSUE THREAD

**Issue by benthetechguy** [Tow-Boot/Tow-Boot#132]
I have Tow-Boot on my Pinebook Pro, with Debian installed to the NVMe and Manjaro ARM to the eMMC.
I want to boot Debian by default, but I can't see a way to change the boot order in Tow-Boot, so I have to press escape to select NVMe every boot.

**Comment by ItsHarper** [comment]
We should also ask the question if NVMe should be prioritized over eMMC. If both are present and bootable, I'd think that the NVMe drive is more likely to be the one that the user wants to boot from, since it's the faster interface.

**Comment by benthetechguy** [comment]
This is definitely a good first step, but I still believe it's important to be able to change the boot order. The only question I have is, where would we store this?

**Comment by ItsHarper** [comment]
Note that I'm not a Tow Boot contributor, but I'm pretty confident that I've seen @samueldr say he wants to implement this feature eventually.

As far as where settings would get stored, see this page: https://github.com/Tow-Boot/Tow-Boot/blob/released/doc/variants.md

I wonder if there's a reason that mmcboot doesn't support saving the environment, or if that will be able to come later, like for shared storage.

**Comment by benthetechguy** [comment]
Ah, so it would be saved to the same place Tow-Boot is stored except for in a read-only noenv situation. That could be problematic for some SPI devices with limited writes.

**Comment by samueldr** [comment]
Yes, such an interface is planned already see #79.

The `mmcboot` variant doesn't support saving the variant for two reasons

  - didn't look into it yet
  - it's not exactly useful yet to save the environment

I have reasons to believe that without #95 it might be harmful to save the environment too eagerly; as it might mean that any changes to the defaults will not be apparent.

Similarly, I fully intend to make environment saving possible with the shared disk strategy, but it requires adding an environment driver that saves into the partition Tow-Boot was loaded from.

* * *

Note that [if you're clever enough you should understand how to manipulate the environment](https://source.denx.de/u-boot/u-boot/-/blob/v2021.10/include/config_distro_bootcmd.h#L496), and you'd be one `env save` away from changing the boot order.

**Comment by benthetechguy** [comment]
Ah, I didn't realize this was a duplicate issue as #79 didn't appear in the quick search I did before opening this. Thanks for the info!
