### ISSUE TITLE
rockpi4c keyboard does not work in installer/early boot

### ISSUE THREAD

**Issue by elizagamedev** [Tow-Boot/Tow-Boot#147]
I tried a number of different keyboards on all of the usb ports as well as trying through a USB hub. The installer was completely unresponsive.

I (maybe irresponsibly) flashed anyway by modifying the installer image to automatically flash at start. The issue persists when booting Linux (NixOS in my case), where the grub menu cannot be navigated since the keyboard does not work.

I don't have a serial cable, unfortunately, so I can't share the logs from my device.

**Comment by Strit** [comment]
Same on rockpi4b for me. At least when booting the spi.installer.img flashed to SD card or eMMC.

**Comment by CRTified** [comment]
This popped up a few times on the matrix channel, too, and IIRC some had luck with "other keyboards". 

I sadly don't know what the reason might be. While I've installed it using UART, I was able to navigate the menu with my keyboard when testing HDMI output.

**Comment by CRTified** [comment]
One thing that I just remembered: Maybe try the other USB ports. There is at one port (top left, upper USB3.0) whose mode (Host vs. Device) is controlled by the small switch below the USB ports.

**Comment by Strit** [comment]
Tried all USB ports, with the switch to right and left. Same outcome.

**Comment by CRTified** [comment]
Strange, but thanks for reporting it.

**Comment by elizagamedev** [comment]
Yeah, I tried all of the USB ports with pretty much every keyboard in my apartment. I really, really wanted to run a home server with rockpi4c + tow-boot + nixos but after a weekend of nothing but fiddling with it I couldn't get something that booted more than once.

**Comment by picnoir** [comment]
I have the same issue with my Rockpi4A. I also tried all the USB ports without success.

**Comment by Tomaszal** [comment]
I am having the same issue with a few different keyboards. Right now my plan is to order keyboards from Amazon & return them if they don't work until I find one that works. Did anyone have any success getting a keyboard to work on Tow-Boot on RockPi4C at all? If so, which keyboard did you use?

**Comment by jirutka** [comment]
I have the same problem on ROCK Pi 4 B+ (v1.73). :(

**Comment by picnoir** [comment]
I still have this issue with a ROCK Pi 4 A+ on the current development branch, ie. including #208. It seems like the `usb start` does not do the trick for that board.

I can definitely briefly see the `usb start` command running at boot, and finding the HID device. Strange…

I had a look at the defconfig file provided by raxda https://github.com/radxa/u-boot/blob/8e67d581610eb7abd97885e1069b94dcf15b592c/configs/rock-pi-4a-rk3399_defconfig . I couldn't find any obivous differences.

Raxda do ship a rockship uboot though. There's quite a lot of rk-specific binaries shipped in the image on top of the mainline uboot. I'm not sure if it could make a difference. :thinking:

**Comment by picnoir** [comment]
So, I went a bit deeper into this issue. I instrumented u-boot to print more logs about the keyboard initialization here: https://github.com/NinjaTrappeur/Tow-Boot/commit/b98e3935d3428d069b1d8aea59f3fdae0cf440f1

I got this at startup:

![IMG_0541](https://user-images.githubusercontent.com/1219785/213473274-629ade68-b1f8-4e4e-aad1-ed0ba661197c.jpg)

(sorry for the screen picture, I don't have the required hardware to connect to the uart console :()

It seems like we end up in this branch: https://github.com/u-boot/u-boot/blob/e092e3250270a1016c877da7bdd9384f14b1321e/common/usb_kbd.c#L550.

It seems like the usb interruption submission `usb_int_msg(dev, data->intpipe, data->new, data->intpktsize, data->intinterval, false)` is failing.

I don't really know what to do with that information for now.

**Comment by picnoir** [comment]
I think I finally understand the issue here.

Out of despair, I tried using all the keyboards I had around. It turns out that one of the keyboards I own happen to work just fine with the current develop branch (!!!).

I dumped the HIDs of the working on non working keyboards.

Working keyboard:

```
[nix-shell:~/code-root/github.com/NixOS/nixpkgs]$ sudo ./result/bin/usbhid-dump -a1:19 | grep -v : | xxd -r -p^C | hidrd-convert -o spec
Usage Page (Desktop),               ; Generic desktop controls (01h)
Usage (Sys Control),                ; System control (80h, application collection)
Collection (Application),
    Report ID (1),
    Report Size (2),
    Report Count (1),
    Logical Minimum (1),
    Logical Maximum (3),
    Usage (Sys Power Down),         ; System power down (81h, one-shot control)
    Usage (Sys Sleep),              ; System sleep (82h, one-shot control)
    Usage (Sys Wake Up),            ; System wake up (83h, one-shot control)
    Input (No Preferred),
    Report Size (6),
    Input (Constant, Variable),
End Collection,
Usage Page (Consumer),              ; Consumer (0Ch)
Usage (Consumer Control),           ; Consumer control (01h, application collection)
Collection (Application),
    Report ID (2),
    Usage Minimum (00h),
    Usage Maximum (0FFFh),
    Logical Minimum (0),
    Logical Maximum (4095),
    Report Count (1),
    Report Size (16),
    Input,
End Collection,
Usage Page (FF00h),                 ; FF00h, vendor-defined
Usage (00h),
Collection (Application),
    Report ID (3),
    Usage Minimum (00h),
    Usage Maximum (0FFFh),
    Logical Minimum (0),
    Logical Maximum (4095),
    Report Count (1),
    Report Size (16),
    Input,
    Usage Minimum (01h),
    Usage Maximum (FFh),
    Logical Minimum (1),
    Logical Maximum (-1),
    Report Size (8),
    Report Count (1),
    Output,
End Collection,
Usage Page (Desktop),               ; Generic desktop controls (01h)
Usage (Keyboard),                   ; Keyboard (06h, application collection)
Collection (Application),
    Usage Page (Keyboard),          ; Keyboard/keypad (07h)
    Usage Minimum (KB Leftcontrol), ; Keyboard left control (E0h, dynamic value)
    Usage Maximum (KB Right GUI),   ; Keyboard right GUI (E7h, dynamic value)
    Logical Minimum (0),
    Logical Maximum (1),
    Report Size (1),
    Report Count (8),
    Input (Variable),
    Report Count (1),
    Report Size (8),
    Input (Constant),
    Report Count (3),
    Report Size (1),
    Usage Page (LED),               ; LEDs (08h)
    Usage Minimum (01h),
    Usage Maximum (03h),
    Output (Variable),
    Report Count (5),
    Report Size (1),
    Output (Constant),
    Report Count (6),
    Report Size (8),
    Logical Minimum (0),
    Logical Maximum (145),
    Usage Page (Keyboard),          ; Keyboard/keypad (07h)
    Usage Minimum (None),           ; No event (00h, selector)
    Usage Maximum (KB LANG2),       ; Keyboard LANG2 (91h, selector)
    Input,
End Collection
```

Non working keyboard:

```
[nix-shell:~/code-root/github.com/NixOS/nixpkgs]$ sudo ./result/bin/usbhid-dump -a1:18 | grep -v : | xxd -r -p^C | hidrd-convert -o spec
Usage Page (FF00h),                 ; FF00h, vendor-defined
Usage (FF00h),
Collection (Application),
    Logical Minimum (0),
    Logical Maximum (255),
    Usage (30h),
    Report Size (8),
    Report Count (8),
    Input (Variable),
    Usage (31h),
    Output (Variable),
End Collection,
Usage Page (Desktop),               ; Generic desktop controls (01h)
Usage (Keyboard),                   ; Keyboard (06h, application collection)
Collection (Application),
    Report ID (5),
    Report Count (112),
    Report Size (1),
    Logical Minimum (0),
    Logical Maximum (1),
    Usage Page (Keyboard),          ; Keyboard/keypad (07h)
    Usage Minimum (KB Leftcontrol), ; Keyboard left control (E0h, dynamic value)
    Usage Maximum (KB Right GUI),   ; Keyboard right GUI (E7h, dynamic value)
    Usage Minimum (None),           ; No event (00h, selector)
    Usage Maximum (KP Equals),      ; Keypad = (67h, selector)
    Input (Variable),
    Report Count (8),
    Input (Constant),
End Collection,
Usage Page (Desktop),               ; Generic desktop controls (01h)
Usage (Sys Control),                ; System control (80h, application collection)
Collection (Application),
    Report ID (2),
    Usage Minimum (Sys Power Down), ; System power down (81h, one-shot control)
    Usage Maximum (Sys Wake Up),    ; System wake up (83h, one-shot control)
    Logical Minimum (0),
    Logical Maximum (1),
    Report Count (3),
    Report Size (1),
    Input (Variable),
    Report Count (1),
    Report Size (5),
    Input (Constant),
End Collection,
Usage Page (Consumer),              ; Consumer (0Ch)
Usage (Consumer Control),           ; Consumer control (01h, application collection)
Collection (Application),
    Report ID (3),
    Usage Minimum (00h),
    Usage Maximum (02FFh),
    Logical Minimum (0),
    Logical Maximum (32767),
    Report Count (1),
    Report Size (16),
    Input,
End Collection,
Usage Page (FF00h),                 ; FF00h, vendor-defined
Usage (01h),
Collection (Application),
    Report ID (6),
    Logical Minimum (0),
    Logical Maximum (255),
    Usage (2Fh),
    Report Count (2),
    Report Size (8),
    Input (Variable),
End Collection,
Usage Page (FF01h),                 ; FF01h, vendor-defined
Usage (01h),
Collection (Application),
    Report ID (7),
    Logical Minimum (0),
    Logical Maximum (255),
    Usage (20h),
    Report Size (8),
    Report Count (7),
    Feature (Variable),
End Collection,
Usage Page (Desktop),               ; Generic desktop controls (01h)
Usage (Keyboard),                   ; Keyboard (06h, application collection)
Collection (Application),
    Usage Page (Keyboard),          ; Keyboard/keypad (07h)
    Usage Minimum (KB Leftcontrol), ; Keyboard left control (E0h, dynamic value)
    Usage Maximum (KB Right GUI),   ; Keyboard right GUI (E7h, dynamic value)
    Logical Minimum (0),
    Logical Maximum (1),
    Report Size (1),
    Report Count (8),
    Input (Variable),
    Report Count (1),
    Report Size (8),
    Input (Constant),
    Report Count (3),
    Report Size (1),
    Usage Page (LED),               ; LEDs (08h)
    Usage Minimum (01h),
    Usage Maximum (03h),
    Output (Variable),
    Report Count (5),
    Report Size (1),
    Output (Constant),
    Report Count (6),
    Report Size (8),
    Logical Maximum (255),
    Usage Page (Keyboard),          ; Keyboard/keypad (07h)
    Usage Minimum (None),           ; No event (00h, selector)
    Usage Maximum (KB LANG2),       ; Keyboard LANG2 (91h, selector)
    Input,
End Collection
```

The main difference seems to be the number of keyboard collections the keyboard declares: 1 for the working keyboard, 2 for the non working ones.

From there, I assume it's more of a u-boot bug (or missing support?) than a tow-boot one? Looking around the codebase, I did not find any other relevant u-boot components to activate wrt. usb hid keyboards management.

**Comment by russnes** [comment]
Same issue here on a ROCK Pi 4 SE, two different keyboards all ports. It looks like @jirutka fixed it in a separate repo? How far away is it to merge the fix and have a new release?

**Comment by picnoir** [comment]
@russnes: the `usb start` preboot command has already been merged to the develop branch: https://github.com/Tow-Boot/Tow-Boot/blob/development/boards/radxa-RockPi4/default.nix#L21 (except it's using the towboot infrastructure to perform the preboot command instead of a plain uboot patch).

As I mentioned above, it doesn't completely fix the issue for me.

**Comment by samueldr** [comment]
Assuming this is fixed, if *this* issue as experience by individuals here is still present, please reopen/ask to reopen. Otherwise, if experiencing something vaguely similar, or really similar, don't hesitate to open a new issue with details!

**Comment by caniko** [comment]
I just had the same issue happen to me on the rockpro64 @samueldr
