### ISSUE TITLE
Odroid N2+ support; N2 version not working

### ISSUE THREAD

**Issue by hwvern** [Tow-Boot/Tow-Boot#170]
N2 version gives error with command sf probe "unrecognized JEDEC id bytes 0b, 60, 17". Installed on my N2+ is chip XT25Q64D (by XTX), with ID "0B 60 17" (see page 19 of datasheet).

**Comment by samueldr** [comment]
In #149 support was added for the SPI Flash chip.

There hadn't been a new release since this was merged. Until now.

 - https://github.com/Tow-Boot/Tow-Boot/releases/tag/release-2021.10-005

Do tell whether this helped or not!

**Comment by hwvern** [comment]
Tested the -005 release on my Odroid N2+. Erasing SPI-Flash, installing Tow-Boot to SPI Flash and booting Tow-Boot all working perfect now. Thanks.
