### ISSUE TITLE
[PinePhone Beta] How to check Two-Boot starts?

### ISSUE THREAD

**Issue by Narann** [Tow-Boot/Tow-Boot#204]
Hello,

First, thanks for putting you efforts in this project.

I have a PinePhone Beta, default installation.

I read [the doc here](https://tow-boot.org/devices/pine64-pinephoneA64.html) and follow every steps. At en end, there is:

> Once installed, remove the installation media, and verify Tow-Boot starts from power-on.

I remove the SD card (the "installation media"?) and rebooted. And it reboot normally, on the current OS, nothings seems to be different.

How can I check Two-Boot is actually installed?

Thanks in advance!

**Comment by kirsle** [comment]
I could tell tow-boot is installed by seeing how many colors the LED light flashes during boot. The stock Pinephone bootloader only used one LED color (might've been red or something, I don't recall).

With tow-boot the LED on the Pinephone/Pro first turns red and then switches to a secondary color depending on what's booting: yellow for internal eMMC, cyan for microSD card (holding Volume Down on boot), blue for USB Mass Storage mode (Volume Up on boot). If your phone is doing all of this then tow-boot looks installed!

**Comment by Narann** [comment]
Thanks, I realize the Red then Yellow/Cyan/Blue had something to do with Tow-Boot, but was not sure. Thanks for the support. :)
