### ISSUE TITLE
Argument mismatch, evaluation error

### ISSUE THREAD

**Issue by piegamesde** [Tow-Boot/Tow-Boot#239]
When I try to evaluate `(import ./default.nix) { silent = false; }` it fails with an evaluation error. At first this was confusing me since the function clearly has such an argument. However the fail happens later in the call of `./support/nix/eval-with-configuration.nix` with the same `args`, which indeed does not have a `silent` argument.

IME, nothing good has ever come out of `@args` argument capturing, and some alternative mechanism should be used here instead.

**Comment by samueldr** [comment]
This was likely leftover from early futzing about with the repo.
