### ISSUE TITLE
Odroid-N2+ boot menu devices are off-by-one

### ISSUE THREAD

**Issue by mth** [Tow-Boot/Tow-Boot#249]
Using the latest 2022.07-006 tow-boot release on Odroid-N2+.

The eMMC menu item tries to boot non-existent device 2 and SD menu item a device 1 which is actually eMMC (as the SD card is device 0). That is, both menu items device number is real_device_number + 1.

I guess that something has gone wrong with the predictable boot order changes.

Adding pictures from TV screen, if needed I can also attach serial console.

![emmc](https://github.com/Tow-Boot/Tow-Boot/assets/10748/fb9c62c4-e77c-45e8-8b9d-fcdf091733cc)
![sd](https://github.com/Tow-Boot/Tow-Boot/assets/10748/690a3525-14fd-4337-a47c-cfd14b4bcb5d)
![env](https://github.com/Tow-Boot/Tow-Boot/assets/10748/ea597570-c5e7-48b6-96fc-8a0310124736)

Selecting eMMC gives -5 error due some unrelated issue. Debian booted from USB using UEFI had same problem when accessing eMMC, but Armbian using its own device tree sees the Foresee HS200 eMMC module fine - I'm suspecting some problem with uboot device tree file when using this module.

Manually invoking `devnum=0; run mmc_boot` worked fine to boot the SD card.

**Comment by mth** [comment]
I fixed it for myself by editing the bootcmd_mmc1 environment variable to use devnum=0 and saving the environment to the spi flash. Same could be done with bootcmd_mmc2 for eMMC, so there is a workaround for the bug using existing images.

**Comment by samueldr** [comment]
Thanks, I'll have to dig and see if something changed in attributing the indexes for amlogic outright, or if it's specific to N2+

**Comment by tpwrules** [comment]
I am running into the same problem on an ODROID C4 which is also Amlogic. Unfortunately there's no flash on that board to save an environment to so I have to downgrade.

As described, manually invoking `devnum=0; run mmc_boot` works fine to boot the SD card.

**Comment by samueldr** [comment]
On ODROID-C4

> my mmc list numbers are the same on -005 and -006 and i have three mmc targets called SD=0, eMMC=1, and (unused)=2.

**Comment by tpwrules** [comment]
With my ODROID-C4, on -005:
```
=> mmc list
sd@ffe05000: 0 (SD)
mmc@ffe07000: 1

=> env print
[...]
target_name_mmc0=SD
target_name_mmc1=eMMC
target_name_mmc2=(Unused)
[...]
```

And on -006:
```
=> mmc list
sd@ffe05000: 0
mmc@ffe07000: 1

=> env print
[...]
target_name_mmc0=(sdio)
target_name_mmc1=SD
target_name_mmc2=eMMC
[...]
```

**Comment by tpwrules** [comment]
I get identical outputs and results on my ODROID-N2 (non plus) with Tow-Boot installed to SPI.

**Comment by samueldr** [comment]
Thanks, that pretty much confirms my two mistakes, compounding:

 - Accidentally not keeping mmc0 in the boot order
 - Messing with the names

The patch at fault is this one:

 - https://github.com/Tow-Boot/Tow-Boot/blob/5194f5721b5703be37bfe473ca9f052a0cad4dc9/support/u-boot/2022.07/patches/0001-meson-Prefer-internal-boot-methods-first.patch

**Comment by CtrlC-Root** [comment]
> I fixed it for myself by editing the bootcmd_mmc1 environment variable to use devnum=0 and saving the environment to the spi flash. Same could be done with bootcmd_mmc2 for eMMC, so there is a workaround for the bug using existing images.

This worked for me as well and I can now boot off the SD card and eMMC correctly on the Odroid-N2 (non-plus) variant.
