### ISSUE TITLE
SPI installer is broken on ODROID-N2+ in development branch

### ISSUE THREAD

**Issue by shvetsnikita** [Tow-Boot/Tow-Boot#269]
Hello!

As I just found out SPI installer is broken on ODROID-N2+ in current development branch. Error message is:

```
Device 0: unknown device
Card did not respond to voltage select! : -110
MMC Device 2 not found
no mmc device at slot 2
```

**Comment by samueldr** [comment]
I'll have to dig into it, but I believe it's just like #268...

Wrong identifiers for devices in the assumptions written as of right now in Tow-Boot.

I need to check the amlogic situation carefully.
