### ISSUE TITLE
v2023-007 release

### ISSUE THREAD

**Issue by samueldr** [Tow-Boot/Tow-Boot#281]
See:

 - https://github.com/Tow-Boot/Tow-Boot/milestone/8

* * *

We're basically there. `-rc3` is what I expect to be release for all devices, except the Pinephone Pro, which will be the only device with changes in `-rc4` (#280).

Report testing in this issue, if you want to help.

## Things to do

 - [x] Merge last PRs in the milestone
 - [x] Testing
 - [x] Prep release notes

* * *

## The big list of testing done

 - odroid-C4 (tpwrules) [Amlogic S905X3]
 - odroid-N2 (tpwrules) [Amlogic S922X]
 - pine64-pinephoneA64 (MoonlightWave-12,  AndreySV)
 - pine64-pinebookPro (samueldr) [Rockchip RK3399]
 - pine64-pinebookA64 (samueldr) [Allwinner A64]
 - libreComputer-rocRk3399PcMezzanine (samueldr) [Rockchip RK3399]
   - (done) Re-test USB input / screen refresh (seemed iffy when driven from serial)
   - (done) Check NVMe (now that I have a testing drive) → broken, but is it a regression? Same on stock U-Boot; PBP does not abort on running `pci`
 - radxa-zero2 [Amlogic A311D] (samueldr)
 - pinephone pro (samueldr)
   - For testing phone ux; additionally this is a device that ***requires*** testing before a release.

(This should be representative enough of what is well-supported.)

**Comment by tpwrules** [comment]
Validated that boot works properly running on an SD card on ODROID-C4.

**Comment by tpwrules** [comment]
Validated that booting the flasher off the MMC image works for ODROID-N2 (non-plus), that I can flash the SPI, then that Tow-Boot can run off SPI and boot MMC.

**Comment by AndreySV** [comment]
@samueldr Is there any Tow-Boot build, that you'd like to be tested? Or should I build it myself?

**Comment by ghost** [comment]
Works with a "PINE64 PinePhone (A64)".

I installed the new Tow-Boot-version with the installer; i could start my PinePhone with it, as usual.
After that, i used the Tow-Boot-Installer to first "Erase eMMC Boot content" and then install Tow-Boot again; that worked too.

I used [this artifact](https://github.com/Tow-Boot/Tow-Boot/actions/runs/6619636882) to test with.
The previously installed version was [the current stable version](https://github.com/Tow-Boot/Tow-Boot/releases/tag/release-2022.07-006).

---

Note:
Sometimes, directly after installing Tow-Boot, i had the usual, random boot-failure that the PinePhone always had; that made it look like it did not work, but it worked well, when i started my PinePhone again.
It may be a good idea to mention the random boot-failures of the PinePhone in the installation-instructions, so people don't assume that Tow-Boot does not work, if it randomly happens then.

**Comment by AndreySV** [comment]
I've tested 2023.07 007-rc3-pre on original PinePhone. I can confirm, that it boots on the device.

1) 2023-007-rc3 detect both board revisions as 1.2. As a result magnetometer isn't working on 1.2b boards.
See https://github.com/Tow-Boot/Tow-Boot/issues/293

2) Maybe it's late for the release, but It would be nice to include arm-trusted-firmware v2.10 into release. It allows to use pstore in the Linux.

**Comment by samueldr** [comment]
> 1. 2023-007-rc3 detect both board revisions as 1.2. As a result magnetometer isn't working on 1.2b boards.

(Sorry if it's a bit late)

@AndreySV: Can you confirm that this is not a *regression* compared to the previous release? If it's not a regression, it'll be handled in the next release cycle.

**Comment by samueldr** [comment]
> It may be a good idea to mention the random boot-failures of the PinePhone in the installation-instructions, so people don't assume that Tow-Boot does not work, if it randomly happens then.

@MoonlightWave-12: Can you describe more about those random boot failures? As many details as you can observe. I'm not sure I know about those "usual" random boot failures.

**Comment by ghost** [comment]
Sometimes when starting my PinePhone (Manjaro Community Edition, 1.2b), ~~during the time when the notification-LED is normally red,~~ shortly after the LED turns orange, the LED begins to blink in red and the PinePhone will vibrate 10 times, after that the PinePhone will turn off.

This issue happens randomly, and has been happening since i have the PinePhone (originally without tow-boot).

When it starts normally, the LED will turn orange at that point and the PinePhone will only vibrate once, to then continue to start normally.

https://github.com/Tow-Boot/Tow-Boot/assets/123384363/a8d721f6-1571-448b-bbc0-6a1d77c6df88

**Comment by samueldr** [comment]
> will vibrate 10 times

Interesting... This signals that Tow-Boot is fully running, but found nothing out of the default boot chain to boot (and then shuts down to not drain the battery).

I'll try booting a few times. What distribution are you using? Installed to eMMC or to SD?

**Comment by ghost** [comment]
Mobian Testing.
I installed it with the [installer for Mobian 12.0](https://images.mobian.org/pinephone/installer/) to the internal storage (eMMC) with encryption, and then updated to Mobian Testing.
If i remember correctly, that issue also happened with the pre-installed Manjaro, but that was a long time ago.

My PinePhone is the version with 3GB of RAM and 32GB of eMMC-data-storage.

---
Logs:
<details>

Boot-failure
---
```
Tow-Boot SPL 2023.07
DRAM: 3072 MiB
Trying to boot from MMC2
NOTICE:  BL31: v2.9(release):
NOTICE:  BL31: Built : 00:00:00, Jan  1 1980
NOTICE:  BL31: Detected Allwinner A64/H64/R18 SoC (1689)
NOTICE:  BL31: Found U-Boot DTB at 0x20a19d8, model: Pine64 PinePhone (1.2)


Tow-Boot 2023.07 007-rc3-CI [variant: mmcboot]

CPU:   Allwinner A64 (SUN50I)
Model: Pine64 PinePhone (1.2)
DRAM:  3 GiB
Core:  75 devices, 21 uclasses, devicetree: separate
WDT:   Not starting watchdog@1c20ca0
MMC:   mmc@1c0f000: 0, mmc@1c10000: 2, mmc@1c11000: 1
Loading Environment from nowhere... OK
In:    serial
Out:   serial
Err:   serial
Net:   No ethernet found.
Please press [ESCAPE] or [CTRL+C] to enter the boot menu.
off
off
Adding partition for mmc@1c11000.blk:1 failed
switch to partitions #0, ERROR
MMC: no card present
No ethernet found.
missing environment variable: pxeuuid
Retrieving file: pxelinux.cfg/00000000
No ethernet found.
Retrieving file: pxelinux.cfg/0000000
No ethernet found.
Retrieving file: pxelinux.cfg/000000
No ethernet found.
Retrieving file: pxelinux.cfg/00000
No ethernet found.
Retrieving file: pxelinux.cfg/0000
No ethernet found.
Retrieving file: pxelinux.cfg/000
No ethernet found.
Retrieving file: pxelinux.cfg/00
No ethernet found.
Retrieving file: pxelinux.cfg/0
No ethernet found.
Retrieving file: pxelinux.cfg/default-arm-sunxi-sunxi
No ethernet found.
Retrieving file: pxelinux.cfg/default-arm-sunxi
No ethernet found.
Retrieving file: pxelinux.cfg/default-arm
No ethernet found.
Retrieving file: pxelinux.cfg/default
No ethernet found.
Config file not found
No ethernet found.
No ethernet found.

ERROR: Could not boot anything from distro_bootcmd.

poweroff ...

```

Booting normally
---
```
Tow-Boot SPL 2023.07
DRAM: 3072 MiB
Trying to boot from MMC2
NOTICE:  BL31: v2.9(release):
NOTICE:  BL31: Built : 00:00:00, Jan  1 1980
NOTICE:  BL31: Detected Allwinner A64/H64/R18 SoC (1689)
NOTICE:  BL31: Found U-Boot DTB at 0x20a19d8, model: Pine64 PinePhone (1.2)


Tow-Boot 2023.07 007-rc3-CI [variant: mmcboot]

CPU:   Allwinner A64 (SUN50I)
Model: Pine64 PinePhone (1.2)
DRAM:  3 GiB
Core:  75 devices, 21 uclasses, devicetree: separate
WDT:   Not starting watchdog@1c20ca0
MMC:   mmc@1c0f000: 0, mmc@1c10000: 2, mmc@1c11000: 1
Loading Environment from nowhere... OK
In:    serial
Out:   serial
Err:   serial
Net:   No ethernet found.
Please press [ESCAPE] or [CTRL+C] to enter the boot menu.
off
off
switch to partitions #0, OK
mmc1(part 0) is current device
Scanning mmc 1:1...
Found /extlinux/extlinux.conf
Retrieving file: /extlinux/extlinux.conf
U-Boot menu
1:	Mobian GNU/Linux 6.6-sunxi64
2:	Mobian GNU/Linux 6.1-sunxi64
Enter choice: 1:	Mobian GNU/Linux 6.6-sunxi64
Retrieving file: /vmlinuz-6.6-sunxi64
Retrieving file: /initrd.img-6.6-sunxi64
append: root=/dev/mapper/calamares_crypt consoleblank=0 loglevel=7 ro quiet splash plymouth.ignore-serial-consoles vt.global_cursor_default=0
Retrieving file: /dtb-6.6-sunxi64/allwinner/sun50i-a64-pinephone-1.2.dtb
   Uncompressing Kernel Image
Moving Image from 0x40080000 to 0x40200000, end=41830000
## Flattened Device Tree blob at 4fa00000
   Booting using the fdt blob at 0x4fa00000
Working FDT set to 4fa00000
   Loading Ramdisk to 44ac2000, end 49fff190 ... OK
   Loading Device Tree to 0000000044ab1000, end 0000000044ac1169 ... OK
Working FDT set to 44ab1000

Starting kernel ...

[    9.549177] lima 1c40000.gpu: error -ENODEV: _opp_set_regulators: no regulator (mali) found
[   10.030745] panel-sitronix-st7703 1ca0000.dsi.0: mipi_dsi_attach failed (-517). Is host ready?
[   10.675037] panel-sitronix-st7703 1ca0000.dsi.0: mipi_dsi_attach failed (-517). Is host ready?
[   10.723078] panel-sitronix-st7703 1ca0000.dsi.0: mipi_dsi_attach failed (-517). Is host ready?
[   10.758856] panel-sitronix-st7703 1ca0000.dsi.0: mipi_dsi_attach failed (-517). Is host ready?
[   10.810237] panel-sitronix-st7703 1ca0000.dsi.0: mipi_dsi_attach failed (-517). Is host ready?
[   10.820812] panel-sitronix-st7703 1ca0000.dsi.0: mipi_dsi_attach failed (-517). Is host ready?
[   10.831582] panel-sitronix-st7703 1ca0000.dsi.0: mipi_dsi_attach failed (-517). Is host ready?
[   10.920467] pinephone-keyboard 3-0015: Failed to read device ID: -6
[   10.985156] panel-sitronix-st7703 1ca0000.dsi.0: mipi_dsi_attach failed (-517). Is host ready?

```

</details>

**Comment by samueldr** [comment]
I've hidden your reply, and opened an issue to try and keep track of this, considering it is not a regression. Thank you for the all the information, it will help ensuring I reproduced the right issue.

**Comment by AndreySV** [comment]
> > 1. 2023-007-rc3 detect both board revisions as 1.2. As a result magnetometer isn't working on 1.2b boards.
> 
> (Sorry if it's a bit late)
> 
> @AndreySV: Can you confirm that this is not a _regression_ compared to the previous release? If it's not a regression, it'll be handled in the next release cycle.

This is not a regression. Let's do that in the next cycle.
