### ISSUE TITLE
[pine64-pinebookpro] spi partitions

### ISSUE THREAD

**Issue by reukiodo** [Tow-Boot/Tow-Boot#342]
The SPI chip in the Pinebook Pro is 16MB. Tow-Boot on SPI should be less than 2MB from what I can tell. This still leaves ~14MB free in the SPI.

Is it possible to segment the SPI such that Tow-Boot can still boot from it, but something like OpenWrt can also live on the SPI flash in a separate space (so each can be updated separately) and used as a fall-back OS to boot?

**Comment by samueldr** [comment]
Possible yes. Out of scope for Tow-Boot though.

* * *

(A few hints and tips)

Nothing about that is specific to Tow-Boot. It's a generic U-Boot thing.

Be mindful about writable filesystems on SPI flash: reports are common that this type of flash *will* wear out. So make such a system entirely stateless.

Be mindful that future Tow-Boot updates [or any platform firmware you are not controlling yourself] may end-up encroaching on whatever space you've set aside for yourself!

* * *

(Closing, but don't take it as a negative; there's nothing *to do* here about this :))
