### ISSUE TITLE
Shared Storage guidance (fdisk warns about GPT?)

### ISSUE THREAD

**Issue by colemickens** [Tow-Boot/Tow-Boot#52]
Hi.

Maybe this is because my SD came pre-formatted, but after I `dd` the rpi4 `shared.disk-image.img` to my SD Card... I figured I'd fire up `fdisk` to add a traditional `/boot` and `/root` for a shared media install.

However, fdisk gave me this warning, and I'm not actually sure what I want to do here:

```
/home/cole/downloads/raspberryPi-aarch64-2021.04-002> sudo dd if=shared.disk-image.img of=/dev/sdb bs=4M; sudo sync; sync
8+1 records in
8+1 records out
34620416 bytes (35 MB, 33 MiB) copied, 0.018304 s, 1.9 GB/s
```

```
/home/cole/downloads/raspberryPi-aarch64-2021.04-002> sudo fdisk /dev/sdb

Welcome to fdisk (util-linux 2.36.2).
Changes will remain in memory only, until you decide to write them.
Be careful before using the write command.

The backup GPT table is not on the end of the device. This problem will be corrected by write.
A hybrid GPT was detected. You have to sync the hybrid MBR manually (expert command 'M').
```

Any tips? Should I ignore it? Should I have "wiped" the sd card more thoroughly?

**Comment by samueldr** [comment]
> The backup GPT table is not on the end of the device

That's expected, as the image wasn't the exact size of your storage medium.

> A hybrid GPT was detected. You have to sync the hybrid MBR manually (expert command 'M').

This one sounds like it means "if you edit the GPT the MBR data will not be synchronized", which is fine as long as you don't edit the size or location of the Tow-Boot partition.

> Should I have "wiped" the sd card more thoroughly?

If my understanding of the latter message is right, and I am sure about the former, nothing you could have done would have changed this, except *correcting by writing*, basically using any partitioning tool to write the backup GPT.

Note that this first message would be present for any GPT-formatted disk written similarly.

**Comment by flokli** [comment]
So is this a matter of "documenting how to get from flashing the shared storage to installing the rest of the OS"?

 - resizing the partition to the physical size (`sgdisk --move-second-header $destination_disk`)
 - making partitions for the OS you want to install (and document expectations w.r.t. extlinux-compatible bootloader config)
