### ISSUE TITLE
Fix RK3399 eMMC PHY power cycling

### ISSUE THREAD

**Issue by 13werwolf13** [Tow-Boot/Tow-Boot#80]
as I understand it, one important patch is missing on the tow-boot.
https://patchwork.ozlabs.org/project/uboot/patch/20220116201814.11672-3-alpernebiyasak@gmail.com/

more can be read in the latest posts in this thread:
https://bugzilla.opensuse.org/show_bug.cgi?id=1194491

**Comment by samueldr** [comment]
The patch is already present in release 004, with the required changes to make it work picked before.

 - https://github.com/Tow-Boot/Tow-Boot/blob/eb2a83466e220e31b561955b2c59b9fc9c21cd46/support/builders/rockchip-rk3399/default.nix#L112-L116
