### ISSUE TITLE
feature request: (hack) u-boot passes its version as a kernel parameter

### ISSUE THREAD

**Issue by colemickens** [Tow-Boot/Tow-Boot#82]
As discussed in "NixOS on ARM" room, and related to my goal of automated testing of new u-boot builds, I would like to know what build of u-boot was used to boot the kernel.

The feature request is a hack, inferior to passing information along via DTB, but is probably more easily implemented today, depending on the u-boot extlinux handling code.

This would allow me to install a new u-boot build, "tryboot" it on rpi4, and then know from the booted system that I succesfully booted via the new build, rather than being booted because the WD kicked in and then the normal u-boot booted.

**Comment by colemickens** [comment]
I think this variable: https://source.denx.de/u-boot/u-boot/-/blob/761a1786e125ce0e2f472f25f2b841d5f4e2f0cb/env/Kconfig#L822

Could be appended in here: https://source.denx.de/u-boot/u-boot/-/blob/761a1786e125ce0e2f472f25f2b841d5f4e2f0cb/boot/pxe_utils.c#L516

**Comment by samueldr** [comment]
As a kernel parameter, I don't like the idea.

Through other means, I'm all for it.

I wonder if the DT spec should even specify such a list of properties.

I know *EFI* itself has some way to do it, `efi: EFI v2.40 by American Megatrends` is logged at `0.00000` during boot. I know U-Boot provides a string for that, though IIRC it's not the actual version used, but a "compatible" version number.

Furthermore, my ACPI x86_64 systems all have [DMI information](https://en.wikipedia.org/wiki/Desktop_Management_Interface) at `/sys/class/dmi/id`. Could DMI itself directly be used for DT systems too? Or maybe not DMI *itself*, but the fields from it?

```
@DUFFMAN .../dmi/id $ for f in *; do echo -n "$f: "; cat $f; done
bios_date: 06/01/2016
bios_release: 3.90
bios_vendor: Hewlett-Packard
bios_version: J61 v03.90
```

Other fields may be useful to have, too:

```
@DUFFMAN .../dmi/id $ for f in *; do echo -n "$f: "; cat $f; done
board_asset_tag: DUFFMAN
board_name: 1589
board_serial: cat: board_serial: Permission denied
board_vendor: Hewlett-Packard
board_version: 0.00
chassis_asset_tag: DUFFMAN
chassis_serial: cat: chassis_serial: Permission denied
chassis_type: 6
chassis_vendor: Hewlett-Packard
chassis_version: 
power: cat: power: Is a directory
product_family: 103C_53335X G=D
product_name: HP Z420 Workstation
product_serial: cat: product_serial: Permission denied
product_sku: B2B96UT#ABA
product_uuid: cat: product_uuid: Permission denied
product_version: 
sys_vendor: Hewlett-Packard
```

Not forgetting we have *some* information about the device already

  - https://github.com/torvalds/linux/blob/e6251ab4551f51fa4cee03523e08051898c3ce82/arch/arm64/boot/dts/rockchip/rk3399-pinebook-pro.dts#L18-L20

**Comment by samueldr** [comment]
Since then, we do provide DMI information. It should be sufficient.

There's also uSWID support if scanning the blob is an acceptable alternative.

(Do feel free to elaborate if it's not sufficient.)
